backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "img" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow # Allows you to save drafts for posts

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "layout", name: "layout", widget: "hidden", default: "layouts/post.njk" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Books in my library
  - name: "library"
    label: "Book"
    folder: "books"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Date Published", name: "publishDate", widget: "date" }
      - { label: "Pages", name: "pages", widget: "number" }
      - { label: "Is Checked Out", name: "checkedOut", widget: "boolean", default: false }
      - { label: "Checked Out By", name: "checkedOutName", widget: "string", optional: true }
      - { label: "Genres", name: "genres", widget: "list", optional: true }
      - { label: "Tags", name: "tags", widget: "list", optional: true }
      - { label: "Edition", name: "tags", widget: "list", optional: true }
      - { label: "Publisher", name: "publisher", widget: "string", optional: true }
      - { label: "Language", name: "language", widget: "string", optional: true }
      - { label: "Language", name: "language", widget: "string", default: "en" }